[LIBPA_0]
loglevel:    LOG_INFO LOG_WARN LOG_MIN LOG_MAJ LOG_CRIT LOG_DEB0 LOG_DEB1 LOG_DEB2 LOG_DEB3
logformat:   DATE
logsize:     30000000
procmask:    APP
destmask:    FILE
destfile:    ./LIBPA_TEST.log 
#destaddr:    localhost:5000:TCP
